# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Tom Eggington
tagline:          ''
description:      ''
url:              https://www.tomeggington.co.uk/

author:
  name:           'Tom Eggington'
  url:            https://www.tomeggington.co.uk

paginate:         1

plugins:          [jekyll-paginate]