#!/usr/bin/env bash
# =============================================================================
# Self-host the site's Google Fonts.
#
# Downloads the woff2 files for Instrument Sans and Instrument Serif into
# assets/fonts/ and writes css/fonts.css with @font-face rules pointing at
# them. Then set `local_fonts: true` in _config.yml and the build stops
# referencing Google entirely.
#
# Run from anywhere (Git Bash or WSL on Windows):  bash scripts/fetch-fonts.sh
# Safe to re-run; it overwrites its own previous output.
# =============================================================================
set -euo pipefail

# A browser UA so Google serves woff2 rather than ttf.
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"

# Keep in step with the families/weights in _includes/head.html.
CSS_URL='https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400;0,500;0,600;1,400&family=Instrument+Serif:ital@0;1&display=swap'

cd "$(dirname "$0")/.."
mkdir -p assets/fonts

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo "Fetching font CSS from Google Fonts..."
curl -fsSL -A "$UA" "$CSS_URL" -o "$tmp"

if ! grep -q '\.woff2' "$tmp"; then
  echo "ERROR: response contains no woff2 URLs (got ttf fallback?). Aborting." >&2
  exit 1
fi

echo "Downloading font files..."
grep -o 'https://fonts\.gstatic\.com/[^)]*\.woff2' "$tmp" | sort -u | while read -r url; do
  file="assets/fonts/$(basename "$url")"
  echo "  $file"
  curl -fsSL -A "$UA" "$url" -o "$file"
done

echo "Writing css/fonts.css..."
{
  echo "/* =========================================================================="
  echo "   Self-hosted fonts. GENERATED by scripts/fetch-fonts.sh — do not edit."
  echo "   Served when local_fonts: true in _config.yml."
  echo "   ========================================================================== */"
  sed 's#https://fonts\.gstatic\.com/[^)]*/\([^/)]*\.woff2\)#/assets/fonts/\1#g' "$tmp"
} > css/fonts.css

echo
echo "Done. Now set 'local_fonts: true' in _config.yml and commit:"
echo "  assets/fonts/  css/fonts.css  _config.yml"
